python3 main.py -dataset 'ICEWS14' \
                -src_descrip_max_length 40 \
                -tgt_descrip_max_length 40 \
                -temporal  \
                -use_soft_prompt \
                -use_rel_prompt_emb \
                -num_beams 40 \
                -eval_tgt_max_length 26 \
                -model_path "checkpoint/ICEWS14-2023-12-01 00:46:11.756703/ICEWS14-epoch=080-val_mrr=0.5995.ckpt" \
                -use_prefix_search \
                -gpu 3